test: 💍 e2e tests for extraction modal
keen/explorer pull request #620
Opened 2021-04-29 12:34 UTC by apryka

2021-04-30 08:56 UTC, mczapkowicz approved these changes

2021-05-04 06:40 UTC, maciejrybaniec requested changes

2021-05-04 06:40 UTC, maciejrybaniec commented on cypress/integration/editor/Extraction.feature
> +  Scenario: Perform test for selecting more properties than confirmExtractionLimit
The scenario description should be written in `business` way without any implementation details like for eg. reference to variable names etc.
So this example scenario description could be like this: Shows extraction confirmation modal when count of properties exceed the limit

2021-05-05 10:11 UTC, maciejrybaniec approved these changes

2021-05-05 10:11 UTC, merged