feat: 🎸 Handling empty event streams
keen/explorer pull request #639
Opened 2021-05-13 10:47 UTC by mczapkowicz

2021-05-14 07:08 UTC, maciejrybaniec requested changes

2021-05-14 07:08 UTC, maciejrybaniec commented on src/components/BrowserPreview/utils/getMissingEventStreams.ts
> +  query: SavedQueryListItem,
Please, consider renaming the argument to `savedQuery` - to avoid duplicate property access like `query.query`

2021-05-14 07:08 UTC, maciejrybaniec commented on src/modules/savedQuery/saga/isQueryEditable.ts
> +  let queryHasExistingEventStream;
IMO the better naming could be just `allEventStreamsExist` - returning variable with this name will be self-descriptive. What do You think ?

2021-05-14 09:58 UTC, mczapkowicz commented on public/locales/en/translation.json
> +    "the_event_stream_do_not_exist": "The {{stream}} event stream used in this query does not exist"
The values will be comma separated by default. In newest commit I've added spaces between commas, pluralization and made part of the string bold like on mockups.

2021-05-14 11:23 UTC, maciejrybaniec requested changes

2021-05-14 11:23 UTC, maciejrybaniec commented on cypress/integration/browser/EmptyEventsStreams.feature
> +Feature: Empty event stream
Disable saved query edit

2021-05-14 11:23 UTC, maciejrybaniec commented on cypress/integration/browser/EmptyEventsStreams.feature
> +    When I click on query with empty event stream
**When** I select saved query that is build on a event stream that do not exist

2021-05-14 11:23 UTC, maciejrybaniec commented on cypress/integration/browser/EmptyEventsStreams.feature
> +  Scenario: Needless UI elements are hidden and edit button is disabled
I suggest update description to something like this: User is not allowed to edit saved query
The rest test conditions are described in **And** cases.

2021-05-14 11:26 UTC, maciejrybaniec requested changes

2021-05-14 11:26 UTC, maciejrybaniec commented on cypress/integration/browser/EmptyEventsStreams.feature
> +Feature: Empty event stream
Additionally the file name could be just EditQuery.feature as empty event stream is not a feature but a state.

2021-05-14 14:00 UTC, maciejrybaniec approved these changes

2021-05-18 07:41 UTC, merged

2021-05-18 07:42 UTC, apryka commented on public/locales/en/translation.json
> +    "the_event_stream_do_not_exist": "The <bold>{{stream}}</bold> event stream used in this query does not exist",
there is no `<bold>` element in HTML, do you mean `<b>`?

is it rendered as HTML string?