FEE-764 update saved query
keen/explorer pull request #681
Opened 2021-08-24 10:38 UTC by apryka

* https://metakeen.atlassian.net/browse/FEE-764
* https://metakeen.atlassian.net/browse/FEE-763

2021-08-25 06:49 UTC, mczapkowicz commented on src/components/BrowserPreview/components/DashboardsConnection/DashboardsConnection.tsx
> +  const isConntectedDashboardsLoading = useSelector(
typo - is**Conntected**DashboardsLoading

2021-08-25 06:49 UTC, mczapkowicz commented on src/components/EditorNavigation/EditorNavigation.tsx
> +  const isConntectedDashboardsLoading = useSelector(
typo

2021-08-25 06:49 UTC, mczapkowicz commented on src/components/UpdateSavedQueryModal/UpdateSavedQueryModal.test.tsx
> +    // },
this can be deleted

2021-08-25 06:49 UTC, mczapkowicz commented on src/components/UpdateSavedQueryModal/UpdateSavedQueryModal.tsx
> +  const isConntectedDashboardsError = useSelector(
typo

2021-08-25 07:14 UTC, mczapkowicz approved these changes

2021-08-25 09:59 UTC, dariuszlacheta submitted a review, later dismissed

2021-08-25 11:17 UTC, mczapkowicz approved these changes

2021-08-30 07:52 UTC, maciejrybaniec requested changes

2021-08-30 07:52 UTC, maciejrybaniec commented on src/modules/app/appSaga.ts
> +  yield takeLatest(SAVE_EXISTING_QUERY, saveExistingQuery);
IMO we should not creating separate action for `saving existing query` - as later in the UI the devs will need to consider this both scenarios. 

There should be only one action responsible for **Saving Query** and the different flows should be executed inside saga based on conditions (exist or not exist).

2021-09-03 13:04 UTC, maciejrybaniec approved these changes

2021-09-03 13:08 UTC, merged